default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: sunset_rider_development
test:
  <<: *default
  database: sunset_rider_test
production:
  <<: *default
  database: pizza_delivery_boy_production
  username: pizza_delivery_boy
  password: <%= ENV['PIZZA_DELIVERY_BOY_DATABASE_PASSWORD'] %>
